### PR TITLE
Added Leetcode DSA interview problem of Binary Tree with solution

### PR DESCRIPTION
**Pull request by amitShindeGit**
Easy level DSA problem from Leetcode.
Data Structure: Binary Tree

### CODE REVIEW

**Comment by rajatbh21** [comment]
Please add the whole code, also with the question and sample test case

**Comment by amitShindeGit** [comment]
Why have you labeled my PR invalid man, nothing was specified as such in your contributing.md file when i made PR .I will make changes just remove the invalid tag what is wrong with you.

**Comment by rajatbh21** [comment]
It is a thing of common sense, you can't just add a function and make the PR. It should have a complete code.

**Comment by amitShindeGit** [comment]
> It is a thing of common sense, you can't just add a function and make the PR. It should have a complete code.

First of all, you are a nonsense guy. And I am raising a ticket against your Repo. Learn how to maintain a repo first.
Second, it is you duty to specify whatever is required from other contributors.You have specified "submit codes related to common interview questions" and that I did from Leetcode with link of the question as well.
No doubt you have no contributors.

**Comment by amitShindeGit** [comment]
And what kind of a fool merges a piece of code and then raises invalid tag without even reverting the PR. Please go and watch Github tutorials.

**Comment by rajatbh21** [comment]
First of all, be respectful. Second of all, if you don't have that much of common sense, then it is futile contributing.

**Pull request merged**
